// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFm0aSzD5vfujMyG8AD6StXtD1VOQZ-A',
    appId: '1:826963184977:web:caf1e589c36197970cd770',
    messagingSenderId: '826963184977',
    projectId: 'notificationflutter-46d4f',
    authDomain: 'notificationflutter-46d4f.firebaseapp.com',
    storageBucket: 'notificationflutter-46d4f.firebasestorage.app',
    measurementId: 'G-HJ03XE0KGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA1rcWfiyHD-n0UNXcXIZz5s1ZIKxSy10',
    appId: '1:826963184977:android:c7cdf37097dda8a80cd770',
    messagingSenderId: '826963184977',
    projectId: 'notificationflutter-46d4f',
    storageBucket: 'notificationflutter-46d4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZnL0hesqhCapAJTW0DRfOboQwAtFn7Cc',
    appId: '1:826963184977:ios:94512f5c0da8c3510cd770',
    messagingSenderId: '826963184977',
    projectId: 'notificationflutter-46d4f',
    storageBucket: 'notificationflutter-46d4f.firebasestorage.app',
    iosBundleId: 'com.example.androidFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZnL0hesqhCapAJTW0DRfOboQwAtFn7Cc',
    appId: '1:826963184977:ios:94512f5c0da8c3510cd770',
    messagingSenderId: '826963184977',
    projectId: 'notificationflutter-46d4f',
    storageBucket: 'notificationflutter-46d4f.firebasestorage.app',
    iosBundleId: 'com.example.androidFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPFm0aSzD5vfujMyG8AD6StXtD1VOQZ-A',
    appId: '1:826963184977:web:d21a2fbfaf6660dc0cd770',
    messagingSenderId: '826963184977',
    projectId: 'notificationflutter-46d4f',
    authDomain: 'notificationflutter-46d4f.firebaseapp.com',
    storageBucket: 'notificationflutter-46d4f.firebasestorage.app',
    measurementId: 'G-R850Y5KFF4',
  );

}